### PR TITLE
feat: filegroup that transitions to target platform

### PR DESCRIPTION
**Pull request by f0rmiga**
The `platform_transition_filegroup` rule takes `srcs` and transitions them to the `target_platform`. See the updated example. After a regular `bazel build //...`, transferred the output `.tar` to a Raspberry Pi and ran successfully.

### CODE REVIEW

**Comment by alexeagle** [comment]
Maybe we'd want this to live in aspect_bazel_lib for general reuse?

**Comment by alexeagle** [comment]
@gregmagolan confirms he'd already like a transition filegroup for some web code at RH, so we should put that in bazel-lib

**Comment by alexeagle** [comment]
https://github.com/aspect-build/bazel-lib/pull/55 for the better home

**Review by alexeagle — APPROVED** [review]

**Comment by f0rmiga** [comment]
@alexeagle thank you for fixing this while I was away.

**Pull request merged**
