### PR TITLE
add/fix support for bazel coverage

### PR DESCRIPTION
**Pull request by tobithiel**
### Type of change

`bazel coverage <...>` with C/C++ targets was not working because the `gcov` binary was not included in the runfiles. This was showing as a silent failure as an empty coverage report. The test log contains:

```
GCov does not exist at the given path: 'external/gcc_toolchain_x86_64/bin/gcov'
```

### Test plan

- Manual testing with

```bash
$ bazel coverage --instrument_test_targets --combined_report=lcov //examples/hello_world_cpp:hello_world_cpp_test
$ genhtml --output genhtml "$(bazel info output_path)//_coverage/_coverage_report.dat"
```

### CODE REVIEW

**Comment by f0rmiga** [comment]
Thanks for this! I think it makes sense to change one of the CI targets to call `bazel coverage` instead of `bazel test`. I can do it after we merge this, no problem.

**Comment by tobithiel** [comment]
> Thanks for this! I think it makes sense to change one of the CI targets to call `bazel coverage` instead of `bazel test`. I can do it after we merge this, no problem.

No problem, thanks for the project. I gave it a try, but I can't really test it since I'm not sure how to actually trigger CI (or don't have permissions to). So feel free to revert and do it differently.

**Comment by f0rmiga** [comment]
I'll get to it today.

**Comment by tobithiel** [comment]
@f0rmiga Could you take another look please when you have some time? I merged in `main` to resolve the conflicts and use the new CI stuff.

**Comment by f0rmiga** [comment]
Awesome, thanks!

**Review by f0rmiga — APPROVED** [review]

**Pull request merged**
